### ISSUE TITLE
app-misc/clight-4.9 installs .desktop files that do not pass validation

### ISSUE THREAD

**Issue by asarubbo** [ferki/gentoo-overlay#3]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: app-misc/clight-4.9 installs .desktop files that do not pass validation.
Discovered on: amd64 (internal ref: ferki_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/afdaaf4f565dff698c3eeb69757b51b0

**Comment by ferki** [comment]
This has been fixed upstream, and I expect to close this issue upon the next upstream release.
